// Generated by https://quicktype.io

export interface AuthApiResponse{
    access_token: string;
    token_type:   string;
    expires_in:   number;
    user:         User;
}

export interface User {
    name:         string;
    email:        string;
    id:           number;
    status:       string;
    email_verify: boolean;
    last_login:   Date;
    created_at:   Date;
    updated_at:   Date;
}
