// Generated by https://quicktype.io

export interface RegisterResponse {
    name:         string;
    email:        string;
    id:           number;
    status:       string;
    email_verify: boolean;
    last_login:   null;
    created_at:   Date;
    updated_at:   Date;
}
